
# Site Configuration
theme: gjooe

lang: "de"

plugins: []

google_analytics_id:

title: "GrÃ¼ne Jugend OÃ– â€“ Linktree"

avatar: "./images/gjooe-logo.jpeg"

name: "gruenejugendooe"

tagline: >-
  Gemeinsam aktiv fÃ¼r Umwelt, Gerechtigkeit und Vielfalt.

links:
  - link:
      icon: "fa-solid fa-calendar-days"
      text: "Aktuelle Veranstaltungen"
      url: "https://gruene-jugend.at/ooe/termine"
      alt: "Alle kommenden Termine und Events"
      title: "Veranstaltungen der GJOOE"
      target: "_blank"
  - link:
      icon: "fa-brands fa-instagram"
      text: "Instagram"
      url: "https://instagram.com/gj_ooe"
      alt: "Instagram-Profil der GrÃ¼nen Jugend OberÃ¶sterreich"
      title: "gj_ooe auf Instagram"
      target: "_blank"
  - link:
      icon: "fa-brands fa-whatsapp"
      text: "WhatsApp-Community"
      url: "https://chat.whatsapp.com/..."
      alt: "WhatsApp-Gruppe der GJOOE"
      title: "GJOOE WhatsApp-Gruppe"
      target: "_blank"
  - link:
      icon: "fa-solid fa-envelope"
      text: "Kontakt"
      url: "mailto:gjooe@gruene-jugend.at"
      alt: "E-Mail an GJOOE"
      title: "E-Mail schreiben"
      target: "_blank"
  - link:
      icon: "fa-solid fa-person-running"
      text: "Jetzt aktiv werden"
      url: "https://gruene-jugend.at/mitgliedwerden"
      alt: "Mitglied werden bei der GrÃ¼nen Jugend"
      title: "Mitglied werden"
      target: "_blank"

socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://instagram.com/gj_ooe"
      title: "Instagram"
      alt: "gj_ooe"
      target: "_blank"
  - social:
      icon: "fa-solid fa-envelope"
      url: "mailto:gjooe@gruene-jugend.at"
      title: "E-Mail"
      alt: "gjooe@gruene-jugend.at"
      target: "_blank"

footer: >
  Folge uns auf Social Media oder werde gleich aktiv! ğŸ’šğŸŒâœŠ

copyright: >
  Â© 2025 <a href="https://gruene-jugend.at/ooe" target="_blank">GrÃ¼ne Jugend OberÃ¶sterreich</a>. Inspired by <a href="https://github.com/ZhgChgLi/linkyee">linkyee</a>
